environment: cpu
training:
  epochs: 100
  batch_size: 64
  loss_function: cce
  checkpoint_interval: 0 
model:
  name: vgg16
  num_classes: 10
dataset:
  name: cifar10
  val_split: 0.2
optimizer:
  name: ssgd
  params:
    learning_rate: 0.00001
    momentum: 0.9
    weight_decay: 0.0005
