environment: cpu
training:
  epochs: 100
  batch_size: 64
  loss_function: cce
  checkpoint_interval: 0 
model:
  name: vgg16
  num_classes: 10
dataset:
  name: cifar10
  val_split: 0.2
optimizer:
  name: oktopk
  params:
    learning_rate: 0.00001
    momentum: 0.9
    weight_decay: 0.0005
    density: 0.05
    min_k_layer: 10
    tau: 1024
    tau_prime: 32