environment: cpu
training:
  epochs: 5
  batch_size: 64
  loss_function: cce
  checkpoint_interval: 0 
model:
  name: vgg16
  num_classes: 10
dataset:
  name: cifar10
  val_split: 0.2
optimizer:
  name: oktopk
  params:
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.005
    density: 0.1
    min_k_layer: 10
    tau: 32
    tau_prime: 64